replicaCount: 1

image:
  repository: kubevoyage
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

database:
  type: postgres # default type, can be changed to mysql, sqlite, etc.
  host: localhost
  port: 5432
  user: dbuser
  password: dbpassword
  name: dbname