replicaCount: 1

image:
  repository: kubevoyage
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

auth:
  adminUser:
  adminPassword:

database:
  type: postgres # default type, can be changed to mysql, sqlite, etc.
  host:
  port:
  user:
  password:
  name: