apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubevoyage.fullname" . }}-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
data:
  db-password: {{ .Values.database.password | b64enc | quote }}
  jwt-secret: {{ .Values.additionalEnvVars.jwtSecret }}