apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubevoyage.fullname" . }}-secret
  namespace: {{ .Values.app.namespace }}
type: Opaque
stringData:
  db-password: {{ .Values.database.password }}
  jwt-secret: {{ .Values.additionalEnvVars.jwtSecret }}
  admin-user: {{ .Values.auth.adminUser }}
  admin-password: {{ .Values.auth.adminPassword }}